name: ale
channels:
  - conda-forge
  - default

dependencies:
  - cmake>=3.10
  - eigen
  - gsl
  - jupyter
  - numba
  - numpy
  - openblas>=0.3.0
  - pvl
  - python=3.7.1
  - python-dateutil
  - scipy
  - spiceypy
  - quaternion
  - pyyaml
  - networkx
