name: ale
channels:
  - conda-forge

dependencies:
  - breathe
  - brotli
  - brotli-python
  - cmake>=3.15
  - eigen
  - gdal
  - jupyter
  - networkx
  - nlohmann_json
  - numpy
  - spiceql>=1.2.4
  - pvl
  - pytest
  - pytest-cov
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - requests
  - scipy
  - spiceypy>=6.0.0
