name: ale
channels:
  - conda-forge
  - default

dependencies:
  - cmake>=3.15
  - pytest
  - eigen
  - gdal 
  - jupyter
  - nlohmann_json
  - numpy
  - pvl
  - pytz
  - python
  - python-dateutil
  - scipy>=1.4.0,<1.11
  - spiceypy>=5.1.0
  - pyyaml
  - pytest
  - pytest-cov
  - networkx
  - breathe
  - pip
  - pip:
    - affine6p
