name: ale
channels:
  - conda-forge
  - default
  - usgs-astrogeology

dependencies:
  - cmake>=3.10
  - eigen
  - gsl
  - jupyter
  - nlohmann_json
  - numba
  - numpy
  - openblas>=0.3.0
  - pvl
  - python=3.7.1
  - python-dateutil
  - scipy
  - spiceypy=2.2.2
  - quaternion
  - pyyaml
  - networkx
